service: sls-legendei-descomplica

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  deploymentBucket:
    name: sls-legendei-deplyment-bucket
  environment:
    RDS_HOSTNAME: legendei-app.cgaek3spfsqe.us-east-1.rds.amazonaws.com
    RDS_USERNAME: admin
    RDS_PASSWORD: u#JP6729
    RDS_PORT: 3306
    DATABASE: legendei0-app

functions:
  run:
    handler: handler.run
    events:
      # Invoke Lambda function every 10 minutes
      - schedule: rate(10 minutes)
    vpc:
        securityGroupIds:
          - sg-0a5e8ca68095b1ee6
        subnetIds:
          - subnet-b7b40886
          - subnet-ecfa938a
          - subnet-6ed0ba31
          - subnet-ae57208f
          - subnet-d1b89bdf
          - subnet-ee724aa3

plugins:
  - serverless-deployment-bucket
  - serverless-plugin-typescript